# Generated by Django 4.2.5 on 2023-09-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(default='', max_length=15)),
                ('date', models.DateField()),
                ('maxtemp', models.SmallIntegerField()),
                ('mintemp', models.SmallIntegerField()),
                ('precip', models.SmallIntegerField()),
            ],
        ),
    ]
