# Generated by Django 4.2.5 on 2023-09-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='weatherrecord',
            constraint=models.UniqueConstraint(fields=('station', 'date'), name='unique_date_station_combination'),
        ),
    ]
