# Generated by Django 4.2.5 on 2023-09-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0002_weatherrecord_unique_date_station_combination'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecordAnalyzed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(default='', max_length=15)),
                ('year', models.SmallIntegerField()),
                ('max_temp_ave', models.SmallIntegerField()),
                ('min_temp_ave', models.SmallIntegerField()),
                ('precip_total', models.SmallIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='weatherrecord',
            old_name='maxtemp',
            new_name='max_temp',
        ),
        migrations.RenameField(
            model_name='weatherrecord',
            old_name='mintemp',
            new_name='min_temp',
        ),
        migrations.AddConstraint(
            model_name='weatherrecordanalyzed',
            constraint=models.UniqueConstraint(fields=('station', 'year'), name='unique_year_station_combination'),
        ),
    ]
