# Generated by Django 4.2.5 on 2023-09-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapi', '0003_weatherrecordanalyzed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherrecordanalyzed',
            name='max_temp_ave',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='weatherrecordanalyzed',
            name='min_temp_ave',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='weatherrecordanalyzed',
            name='precip_total',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
